Add 5 laboratory work
Starik1500/Repository-for-HW pull request #1
Opened 2023-11-26 17:30 UTC by Starik1500

Add 5 laboratory work

2023-11-30 10:40 UTC, lettaaaaa requested changes
Перед усіма класами має бути 2 отступи, та перед методами також має бути 2 оступи

2023-11-30 10:40 UTC, lettaaaaa commented on Laba 5.py
> +        if self.mass * self.amount > 2000:
магічне число 2000

2023-11-30 10:40 UTC, lettaaaaa commented on Laba 5.py
> +    def find_the_most_expensive_candies(self, n):
незрозуміла назва перемінної 'n'

2023-11-30 10:40 UTC, lettaaaaa commented on Laba 5.py
> +
має бути 2 отступи

2023-11-30 10:40 UTC, lettaaaaa commented on Laba 5.py
> +
перед класом 2 отступи

2023-11-30 10:40 UTC, lettaaaaa commented on Laba 5.py
> +    def __init__(self, name, mass, amount, price, candy_type):
має бути отступ перед петодом

2023-11-30 10:40 UTC, lettaaaaa commented on Laba 5.py
> +
перед методом 2 отступи

2023-11-30 10:46 UTC, lettaaaaa requested changes

2023-11-30 10:46 UTC, lettaaaaa commented on Laba 5.py
> +    def __init__(self, name, mass, amount, price, candy_type):
забагато аргументів у класі, має бути не більше 5

2023-12-03 19:40 UTC, Starik1500 commented on Laba 5.py
> +
> має бути 2 отступи

додав

2023-12-03 19:40 UTC, Starik1500 commented on Laba 5.py
> +
> перед класом 2 отступи

додав

2023-12-03 19:41 UTC, Starik1500 commented on Laba 5.py
> +    def __init__(self, name, mass, amount, price, candy_type):
> має бути отступ перед петодом

додав

2023-12-03 19:41 UTC, Starik1500 commented on Laba 5.py
> +    def __init__(self, name, mass, amount, price, candy_type):
> забагато аргументів у класі, має бути не більше 5

видалив лишній аргумент та пов'язане з ним

2023-12-03 19:41 UTC, Starik1500 commented on Laba 5.py
> +
додав

2023-12-03 19:41 UTC, Starik1500 commented on Laba 5.py
> +        if self.mass * self.amount > 2000:
додав коментар

2023-12-03 19:41 UTC, Starik1500 commented on Laba 5.py
> +    def find_the_most_expensive_candies(self, n):
перейменував на numbers

2023-12-03 20:12 UTC, lettaaaaa approved these changes

2023-12-10 18:12 UTC, closed without merging

2024-01-06 10:45 UTC, zveres-ss commented on Laba 5.py
> +        if self.mass * self.amount > 2000:
краще 2000 зробити константою

2024-01-06 10:47 UTC, zveres-ss commented on Laba 5.py
> +    Candy4 = Candy("Eclips", 50, 5, 30)
python convention? variable_name_looks_like_this_string
and you have candy name, use this name as variable name

2024-01-06 10:47 UTC, zveres-ss commented on Laba 5.py
> +    Dinner3 = Dinner("Tuesday", "20:00")
monday_dinner
friday_dinner
tuesday_dinner

2024-01-06 10:47 UTC, zveres-ss commented on Laba 5.py
> +    expensive_candies = Dinner1.find_the_most_expensive_candies(3)
here is a point why convention matters: for any experienced reader `Dinner1.find_the_most_expensive_candies(3)` means a call to static method from class Dinner1